name: 'Action Test'
on:
  # Executing action on PR's is not supported. Somehow /nix/store cache gets corrupted. Will fix soon
  #pull_request:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:


jobs:
  discovery: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    outputs:
      hits: ${{ steps.discovery.outputs.hits }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v23
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            trusted-users = runner
            access-tokens = github.com=${{ github.token }}
      - uses: ./discovery
        id: discovery
        with:
          attrPaths: ci.x86_64-linux.default, packages.x86_64-linux
          nixStoreCachingEnabled: false
          nixEvalCacheCachingEnabled: false
        env:
          GITHUB_TOKEN: ${{ github.token }}

  execute-targets:
    name: "${{ matrix.target.attrPath }}"
    needs: [discovery]
    permissions:
      actions: read
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.discovery.outputs.hits) }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v23
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            trusted-users = runner
            access-tokens = github.com=${{ github.token }}
      - uses: ./worker
        id: worker
        with:
          target: ${{ toJSON(matrix.target) }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

